package BD.Util;

public class HTML {
    public static String footer = "<footer class=\"page-footer font-small pt-4\">\n"
            + "                <div class=\"footer-style\">\n"
            + "                    <ul class=\"list-unstyled list-inline text-center\">\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <a class=\"fb-ic\">\n"
            + "                                <i class=\"fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <!-- Twitter -->\n"
            + "                            <a class=\"tw-ic\">\n"
            + "                                <i class=\"fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <!-- Google +-->\n"
            + "                            <a class=\"gplus-ic\">\n"
            + "                                <i class=\"fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <!--Linkedin -->\n"
            + "                            <a class=\"li-ic\">\n"
            + "                                <i class=\"fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <!--Instagram-->\n"
            + "                            <a class=\"ins-ic\">\n"
            + "                                <i class=\"fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li class=\"list-inline-item\">\n"
            + "                            <!--Pinterest-->\n"
            + "                            <a class=\"pin-ic\">\n"
            + "                                <i class=\"fab fa-pinterest fa-lg white-text fa-2x\"> </i>\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                    </ul>\n"
            + "                </div>\n"
            + "                <div class=\"footer-copyright text-center py-3\">\n"
            + "                    © 2020 Copyright\n"
            + "                </div>\n"
            + "            </footer>";
}
